### ISSUE TITLE
Resolution

### ISSUE THREAD

**Issue by Sycodevi** [amayash/tof-frontier-clash-bot#1]
I've ran into a problem here, what resolution are you using for this? I cannot use the script properly due to it.

**Comment by amayash** [comment]
1280x720. Start the program on the main screen.

**Comment by amayash** [comment]
Not in escape, just the character must stand.

**Comment by safdtgx** [comment]
1280x720

**Comment by amayash** [comment]
The game must be revealed, not in alt+tab.
